package persistenciaPck;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

public class TableManager {
	
	public void crearTabla() 
	{
		
		Connection c = DBManager.getInstance().conectarse();
		
		String sqlEdificio = "CREATE TABLE edificio (direccion VARCHAR(256), id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1), unidades INT, PRIMARY KEY (id))";
//		String sqlUsuario = "CREATE TABLE usuarios  (usuario VARCHAR(256), pass VARCHAR(256), permiso INT)";
		String sqlDepto = "CREATE TABLE departamento (id_edificio int, nUnidad int, m2 double,FOREIGN KEY (id_edificio) REFERENCES edificio(id))";
		String sqlFinanzas="CREATE TABLE finanzas (id_edificio int, id_gasto INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1), gasto_ord int, gasto_ext int, año int, mes int, PRIMARY KEY (id_gasto), FOREIGN KEY (id_edificio) "
				+ "REFERENCES edificio(id))";
		try 
		{
			Statement s = c.createStatement();
			s.execute(sqlEdificio);
//			s.execute(sqlUsuario);
			s.execute(sqlDepto);
			s.execute(sqlFinanzas);
			c.commit();

		} catch (SQLException e) 
		{
			try 
			{
				c.rollback();
				e.printStackTrace();
			} catch (SQLException e1) 
			{
				e1.printStackTrace();
			}
		} finally 
		{
			try 
			{
				c.close();
			} catch (SQLException e) 
			{
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}
	
	public void borrarTabla() 
	{

		Connection c = DBManager.getInstance().conectarse();
		
		String sqlEdificio = "DROP TABLE edificio";
//		String sqlUsuario = "DROP TABLE usuario";
		String sqlDepto = "DROP TABLE departamento";
		String sqlFinanzas = "DROP TABLE finanzas";
		
		try 
		{
			Statement s = c.createStatement();
			s.execute(sqlFinanzas);
			s.execute(sqlDepto);
			s.execute(sqlEdificio);
//			s.execute(sqlUsuario);
			
			
			c.commit();
		} catch (SQLException e) 
		{
			try 
			{
				e.printStackTrace();
				c.rollback();
			} catch (SQLException e1) 
			{
				e1.printStackTrace();
			}
		} finally 
		
		{
			try 
			{
				c.close();
			} catch (SQLException e) 
			{
				e.printStackTrace();
			}
		}
	}
}
